### ISSUE TITLE
Regression in 1.2.5: IntegrityError: NOT NULL constraint failed

### ISSUE THREAD

**Issue by karyon** [vandersonmota/model_mommy#252]
I have a model Course with a ForeignKey to Semester (see [here](https://github.com/fsr-itse/EvaP/blob/master/evap/evaluation/models.py#L158)). In a test, i use ```Course.objects.bulk_create([mommy.prepare(Course)])``` to create one course without calling its ```save()``` method. 

this worked until model_mommy 1.2.5 (more specifically, bisection showed it works until 8b1c2e9c020559024c1aa7192b0dfcdae83426cb), where this throws ```django.db.utils.IntegrityError: NOT NULL constraint failed: evaluation_course.semester_id```.

**Comment by vandersonmota** [comment]
@karyon That's unfortunate. =/ Guess we'll have to add a option which keeps default Django 1.8 behaviour for FKs.

* sigh *

**Comment by vandersonmota** [comment]
fixed.

**Comment by karyon** [comment]
your tests are failing, and my issue is not fixed. please let me know if i should help debugging.

**Comment by vandersonmota** [comment]
@karyon i forgot to force django 1.8.5 in the .travis.yml

Have you tried upgrading to django 1.8.5?

**Comment by karyon** [comment]
yes, that was already installed.

**Comment by vandersonmota** [comment]
Well, in earlier version of Django 1.8, they were not allowing unsaved foreign_key assignments, so, during `prepare`, the related instance was saved in order to instantiate the model and make all assignments. This was dropped in Django 1.8.5, removing the need for patching, thus, restoring previous versions behaviour (and breaking your tests)
That said, i think we should add an option to `prepare` which will save the related instances if it is True (default False)

I created an issue to implement this functionality: https://github.com/vandersonmota/model_mommy/issues/258

Thanks @karyon
